# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apl < Formula
  desc "tig-style terminal viewer for Claude Code session logs"
  homepage "https://github.com/cheoljoo/ai-prompt-log"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cheoljoo/ai-prompt-log/releases/download/v0.2.3/apl_0.2.3_darwin_amd64.tar.gz"
      sha256 "13f0e321c0b18eeaf89e09820f8287c3fb7d12b41667acb89b5cadf2eab97930"

      define_method(:install) do
        bin.install "apl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cheoljoo/ai-prompt-log/releases/download/v0.2.3/apl_0.2.3_darwin_arm64.tar.gz"
      sha256 "17ae090a2738393032c5128ded27e27f697354823421ef4b48a9d8f4174ad14b"

      define_method(:install) do
        bin.install "apl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cheoljoo/ai-prompt-log/releases/download/v0.2.3/apl_0.2.3_linux_amd64.tar.gz"
      sha256 "cb172e6f67b34f491ef0a525c5c7f6c8d1284f408cc880f6704ab2e842c0c51d"
      define_method(:install) do
        bin.install "apl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cheoljoo/ai-prompt-log/releases/download/v0.2.3/apl_0.2.3_linux_arm64.tar.gz"
      sha256 "62f8b53cf584a64b437f056e0d47a41048a84458a7402a99d091712182aa955b"
      define_method(:install) do
        bin.install "apl"
      end
    end
  end

  test do
    system "#{bin}/apl --help"
  end
end
