# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apl < Formula
  desc "tig-style terminal viewer for Claude Code session logs"
  homepage "https://github.com/cheoljoo/ai-prompt-log"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cheoljoo/ai-prompt-log/releases/download/v0.2.1/apl_0.2.1_darwin_amd64.tar.gz"
      sha256 "0b7e835587608b08d73fad51d45c50dae0f728a137f1e5dbc7db0a92733e122a"

      define_method(:install) do
        bin.install "apl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cheoljoo/ai-prompt-log/releases/download/v0.2.1/apl_0.2.1_darwin_arm64.tar.gz"
      sha256 "1a204387017b26b03a888d550dc3c07583ae308cd28dbe8d6394498cfccdb900"

      define_method(:install) do
        bin.install "apl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cheoljoo/ai-prompt-log/releases/download/v0.2.1/apl_0.2.1_linux_amd64.tar.gz"
      sha256 "314ac8a98cafaa9a1df04d482c9d2a549a9bf82e3b9d9e4a290b770cc80409bd"
      define_method(:install) do
        bin.install "apl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cheoljoo/ai-prompt-log/releases/download/v0.2.1/apl_0.2.1_linux_arm64.tar.gz"
      sha256 "bce563dc0880efa7ed62ec9af95d030d792e10bef32c672cf6783f8d9734d49e"
      define_method(:install) do
        bin.install "apl"
      end
    end
  end

  test do
    system "#{bin}/apl --help"
  end
end
